apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: isoppfolgingsplan
  namespace: teamsykefravr
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  port: 8080
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 70
  startup:
    path: /internal/is_ready
    periodSeconds: 5
    timeout: 5
    failureThreshold: 30
  liveness:
    path: /internal/is_alive
    periodSeconds: 5
    timeout: 5
    failureThreshold: 3
  readiness:
    path: /internal/is_ready
    periodSeconds: 5
    timeout: 5
    failureThreshold: 3
  leaderElection: true
  prometheus:
    enabled: true
    path: /internal/metrics
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 384Mi
  accessPolicy:
    inbound:
      rules:
        - application: syfomodiaperson
    outbound:
      external:
        - host: "login.microsoftonline.com"
        - host: "ereg-services-q1.dev-fss-pub.nais.io"
        - host: "dokarkiv.dev-fss-pub.nais.io"
      rules:
        - application: istilgangskontroll
  gcp:
    sqlInstances:
      - type: POSTGRES_17
        tier: db-f1-micro
        databases:
          - name: isoppfolgingsplan-db
        diskAutoresize: true
  azure:
    application:
      allowAllUsers: true
      enabled: true
      claims:
        extra:
          - "NAVident"
  kafka:
    pool: nav-dev
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  env:
    - name: KTOR_ENV
      value: "production"
    - name: JOURNALFORING_RETRY_ENABLED
      value: "false"
    - name: DOKARKIV_CLIENT_ID
      value: "dev-fss.teamdokumenthandtering.dokarkiv-q1"
    - name: DOKARKIV_URL
      value: "https://dokarkiv.dev-fss-pub.nais.io"
    - name: EREG_URL
      value: "https://ereg-services-q1.dev-fss-pub.nais.io"
    - name: ISTILGANGSKONTROLL_CLIENT_ID
      value: "dev-gcp.teamsykefravr.istilgangskontroll"
    - name: ISTILGANGSKONTROLL_URL
      value: "http://istilgangskontroll"
